
document.write('<div id="globalNavi"><div class="menuSP_button">Menu</div><nav class="menuSP_navi">');
document.write('<ul class="globalNaviMain">');
document.write('<li><a href="/index.html">ホーム<p class="enText">Home</p></a></li>');
document.write('<li><a href="/company/index.html">企業情報<p class="enText">About Us</p></a>');
document.write('<ul class="globalNaviSub listNo1">');
document.write('<li><a href="/company/index.html">会社概要</a></li>');
document.write('<li><a href="/company/mission.html">企業理念</a></li>');
document.write('<li><a href="/company/history.html">会社沿革</a></li>');
document.write('<li><a href="/company/top_message.html">CEO挨拶</a></li>');
document.write('<li><a href="/company/message.html">役員紹介</a></li>');
document.write('<li><a href="/company/award.html">受賞履歴</a></li>');
document.write('<li><a href="/company/accessmap.html">アクセス</a></li>');
document.write('</ul></li>');
document.write('<li><a href="/service/index.html">事業紹介<p class="enText">Service</p></a>');
document.write('<ul class="globalNaviSub listNo2">');
document.write('<li><ul><li>共通ポイント事業</li>');
document.write('<li><a href="/service/point_exchange.html">ポイント交換サービス</a></li>');
document.write('<li class="ListLower"><a href="/service/point/alliedlist.html">提携加盟サイト一覧</a></li>');
document.write('<li><a href="/service/point_media.html">ポイントメディアサービス</a></li>');
document.write('<li><a href="/service/point_digitalgift.html">デジタルギフトサービス</a></li>');
document.write('<li><a href="/service/payment/index.html">ネットマイル決済サービス</a></li>');
document.write('</ul></li>');
document.write('<li><ul><li>コンテンツ事業</li>');
document.write('<li><a href="/service/contents_game.html">ゲームコンテンツサービス</a></li>');
document.write('</ul></li>');
document.write('<li><ul><li>プロモーション事業</li>');
document.write('<li><a href="/service/promotion_ad.html">アドネットワークサービス</a></li>');
document.write('<li class="ListLower"><a href="/download/mediainfo.pdf" target="_blank">自社メディア媒体資料</a></li>');

document.write('<li class="ListLower"><a href="/download/AdF_network.pdf" target="_blank">協業メディア媒体資料</a></li>');
document.write('</ul></li></ul></li>');
document.write('<li><a href="/news/index.html">ニュース<p class="enText">News</p></a>');
document.write('<ul class="globalNaviSub listNo3"><li><p>プレスリリース</p>');
document.write('<ul class="globalNaviSubPress">');
document.write('<li><a href="/news/index.html">2017</a></li>');
document.write('<li><a href="/news/press_2016.html">2016</a></li>');
document.write('<li><a href="/news/press_2015.html">2015</a></li>');
document.write('<li><a href="/news/press_2014.html">2014</a></li>');
document.write('<li><a href="/news/press_2013.html">2013</a></li>');
document.write('<li><a href="/news/press_2012.html">2012</a></li>');
document.write('<li><a href="/news/press_2011.html">2011</a></li>');
document.write('<li><a href="/news/press_2010.html">2010</a></li>');
document.write('<li><a href="/news/press_2009.html">2009</a></li>');
document.write('<li><a href="/news/press_2008.html">2008</a></li>');
document.write('<li><a href="/news/index.html">2007～</a></li>');
document.write('</ul></li><li><p>パブリシティ</p>');
document.write('<ul class="globalNaviSubPublicity">');
document.write('<li><a href="/news/publicity.html">2017</a></li>');
document.write('<li><a href="/news/publicity_2016.html">2016</a></li>');
document.write('<li><a href="/news/publicity_2015.html">2015</a></li>');
document.write('<li><a href="/news/publicity_2014.html">2014</a></li>');
document.write('<li><a href="/news/publicity_2013.html">2013</a></li>');
document.write('<li><a href="/news/publicity_2012.html">2012</a></li>');
document.write('<li><a href="/news/publicity_2011.html">2011</a></li>');
document.write('<li><a href="/news/publicity_2010.html">2010</a></li>');
document.write('<li><a href="/news/publicity_2009.html">2009</a></li>');
document.write('<li><a href="/news/publicity_2008.html">2008</a></li>');
document.write('<li><a href="/news/publicity.html">2007～</a></li>');
document.write('</ul></li></ul></li>');
document.write('<li><a href="/recruit/index.html">採用情報<p class="enText">Recruit</p></a>');
document.write('<ul class="globalNaviSub listNo4">');
document.write('<li><a href="/recruit/ceo.html">CEOメッセージ</a></li>');
document.write('<li><a href="/company/message.html">役員紹介</a></li>');
document.write('<li><a href="/recruit/office.html">オフィスツアー</a></li>');
document.write('<li><a href="/company/history.html">ネットマイルヒストリー</a></li>');
document.write('<li><a href="/recruit/internship.html">インターンシップ</a></li>');
document.write('<li><a href="/recruit/guide/index.html">募集要項</a></li>');
document.write('</ul></li>');
//資料請求・お問い合わせ
document.write('<li class="contectBtn"><a href="https://www.netmile.co.jp/contact/catalog.htm" target="_blank">資料請求・お問い合わせ<p class="enText">Contact Us</p></a></li>');
document.write('</ul></nav></div>');
document.close();


