document.write('<div class="infooterBox">');
document.write('<div class="footerBizList">');
document.write('<ul>');
document.write('<li><a href="/service/point_digitalgift.html"><dl><dt><img src="/images/common/logo_nmg.svg" alt="ネットマイルギフト" width="150" height="62" /></dt><dd>ユーザーの「欲しいもの」が<br>必ずあるデジタルギフト</dd></dl></a></li>');
document.write('<li><a href="/service/point_media.html"><dl><dt><img src="/images/common/logo_sugutama.svg" alt="すぐたま"  width="150" height="62" /></dt><dd>共通ポイント「ネットマイル」が<br>一番貯まるサイト</dd></dl></a></li>');
document.write('<li><a href="/service/point_exchange.html"><dl><dt><img src="/images/common/logo_nm.svg" alt="ネットマイル" width="150" height="62" /></dt><dd>200種類の交換先を提供する<br>ポイント交換サービス</dd></dl></a></li>');
document.write('<li><a href="/service/contents_game.html"><dl><dt><img src="/images/common/logo_game.svg" alt="Game Factory" width="150" height="62" /></dt><dd>ユーザーの定着化を<br>実現するゲームコンテンツ</dd></dl></a></li>');
document.write('<li><a href="/service/promotion_ad.html"><dl><dt><img src="/images/common/logo_ad.svg" alt="Ad Factory"  width="150" height="62" /></dt><dd>独占配信メディア多数の<br>アドネットワーク</dd></dl></a></li>');
document.write('</ul></div>');
document.write('<div class="contactArea">');
document.write('<p>詳しい資料のご請求やお問い合わせは専用フォームから</p>');
document.write('<p><a href="https://www.netmile.co.jp/contact/catalog.htm" target="_blank" class="contactButton">法人のお客さま専用お問い合わせ</a></p>');
document.write('<p><a href="http://faq.netmile.co.jp" target="_blank">個人会員のお客さまは、「FAQ・お問い合わせ」をご利用ください。</a></p>');
document.write('</div>');
document.write('<div class="footerList"><ul>');
document.write('<li><ul>');
document.write('<li><h3><a href="/company/index.html">企業情報</a></h3></li>');
document.write('<li><a href="/company/index.html">会社概要</a></li>');
document.write('<li><a href="/company/mission.html">企業理念</a></li>');
document.write('<li><a href="/company/history.html">会社沿革</a></li>');
document.write('<li><a href="/company/top_message.html">CEO挨拶</a></li>');
document.write('<li><a href="/company/message.html">役員紹介</a></li>');
document.write('<li><a href="/company/award.html">受賞履歴</a></li>');
document.write('<li><a href="/company/accessmap.html">アクセス</a></li>');
document.write('</ul></li>');
document.write('<li><ul>');
document.write('<li><h3><a href="/service/index.html">事業紹介</a></h3></li>');
document.write('<li class="footerListTitle">共通ポイント事業</li>');
document.write('<li><a href="/service/point_exchange.html">ポイント交換サービス</a></li>');
document.write('<li class="ListLower"><a href="/service/point/alliedlist.html">提携加盟サイト一覧</a></li>');
document.write('<li><a href="/service/point_media.html">ポイントメディアサービス</a></li>');
document.write('<li><a href="/service/point_digitalgift.html">デジタルギフトサービス</a></li>');
document.write('<li class="footerListTitle">コンテンツ事業</li>');
document.write('<li><a href="/service/contents_game.html">ゲームコンテンツサービス</a></li>');
document.write('<li class="footerListTitle">プロモーション事業</li>');
document.write('<li><a href="/service/promotion_ad.html">アドネットワークサービス</a></li>');
document.write('<li class="ListLower"><a href="/download/mediainfo.pdf" target="_blank">自社メディア媒体資料</a></li>');
document.write('<li class="ListLower"><a href="/download/AdF_network.pdf" target="_blank">協業メディア媒体資料</a></li>');
document.write('</ul></li>');
document.write('<li><ul>');
document.write('<li><h3><a href="/news/index.html">ニュース</a></h3></li>');
document.write('<li><a href="/news/index.html">プレスリリース</a></li>');
document.write('<li><a href="/news/publicity.html">パブリシティ</a></li>');
document.write('</ul></li>');
document.write('<li><ul>');
document.write('<li><h3><a href="/recruit/index.html">採用情報</a></h3></li>');
document.write('<li><a href="/recruit/ceo.html">CEOメッセージ</a></li>');
document.write('<li><a href="/company/message.html">役員紹介</a></li>');
document.write('<li><a href="/recruit/office.html">オフィスツアー</a></li>');
document.write('<li><a href="/company/history.html">ネットマイルヒストリー</a></li>');
document.write('<li><a href="/recruit/internship.html">インターンシップ</a></li>');
document.write('<li><a href="/recruit/guide/index.html">募集要項</a></li>');
document.write('</ul></li>');
document.write('<li><ul>');
// document.write('<li><h3><a href="https://www.netmile.co.jp/contact/catalog.htm" target="_blank">資料請求・お問い合わせ</a></h3></li>');
document.write('<li><h3><a href="/policy/privacy.html">プライバシーポリシー</a></h3></li>');
document.write('<li><h3><a href="/sitemap.html">サイトマップ</a></h3></li>');
document.write('<li class="pmarkArea"><a href="http://privacymark.jp/" target="_blank" class="noneIcon">');
document.write('<ul>');
document.write('<li><img src="/images/pmark-r.png" alt="ネットマイルはプライバシーマークを取得しています。" width="62" height="62" /></li>');
document.write('<li class="pmarkAreaTitle">ネットマイルはプライバシーマークを取得しています。</li>');
document.write('</ul></a></li>');
document.write('<li><a href="http://www.jipc.jp/campaign/" target="_blank" class="noneIcon"><img src="/images/bn_excpn080212.gif" alt="不正撲滅キャンペーン「ポイントの不正獲得は犯罪です!!」 " width="160" height="65" /></a></li>');
document.write('</ul></li>');
document.write('</ul>');
document.write('</div><!-- footerList -->');
document.write('</div><!-- infooterBox -->');
document.close();