document.write('<div id="header">');
document.write('<a href="/" name="top"><img src="/images/common/header/companyname.gif" alt="株式会社 ネットマイル" width="219" height="35" border="0" class="companyname"/></a>');
document.write('<div class="headerR">');
document.write('<a href="http://www.netmile.co.jp/" target="_blank"><img src="/images/common/header/logo.gif" alt="NetMile" width="72" height="19" border="0" /></a>');
document.write('<ul>');
document.write('<li><a href="/sitemap.html">サイトマップ</a></li>');
document.write('<li><a href="http://www.netmile.co.jp/" target="_blank">サービスサイト</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('<div class="floatReset"></div>');
document.write('</div>');
document.close();